package(default_visibility = [
    "//java/com/nexus:__subpackages__",
])

java_library(
    name = "inject",
    srcs = glob(["*.java"]),
    deps = [
        "@com_google_inject_guice//jar",
    ],
)
