
java_library(
    name = "service",
    srcs = glob(["*.java"]),
    deps = [
        "//proto/parkingticket/service:address_java_proto",
        "@com_google_inject_guice//jar",
        "@com_google_guava_guava//jar",
        "@io_grpc_grpc_stub//jar",
    ]
)
